### ISSUE TITLE
シフト編集画面で自分が所属していない店舗のシフトにクエリパラメータから飛べないようにする

### ISSUE THREAD

**Issue by JinA293** [nineteen2021/shiftan-v2#258]
現状
・URLのIDを変更することで多店舗のシフト作成画面に飛べる

理想
・シフト編集画面で自分が所属していない店舗のシフトに飛べないようにする

**Comment by yamato3010** [comment]
以下のように飛べないようにできました～
![Animation](https://user-images.githubusercontent.com/75778273/195967019-a429bec7-d653-4132-bd31-4ca2cbd49dae.gif)
